version: '2'
services:
  opms:
    build: ./opms
    ports:
      - "8088:8088"
    depends_on:
      - db
    restart: always
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: engine
    volumes_from:
      - dvc
    restart: always
  dvc:
    build: ./dvc
    command: bash
    
